services:
  postgres:
    image: postgres:16
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    image: ${AIRFLOW_IMAGE_NAME}
    container_name: airflow-init
    depends_on:
      - postgres
    env_file:
      - .env
    environment: &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-api-server:8080/execution/
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET}
      PYTHONPATH: /opt/airflow
    user: "${AIRFLOW_UID}:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./scripts:/opt/airflow/scripts
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username ${_AIRFLOW_WWW_USER_USERNAME}
      --password ${_AIRFLOW_WWW_USER_PASSWORD}
      --firstname Airflow
      --lastname Admin
      --role Admin
      --email admin@example.com
      "

  airflow-api-server:
    image: ${AIRFLOW_IMAGE_NAME}
    container_name: airflow-api-server
    restart: always
    depends_on:
      - postgres
      - airflow-init
    env_file:
      - .env
    environment:
      <<: *airflow-common-env
      PYTHONPATH: /opt/airflow
    user: "${AIRFLOW_UID}:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    command: api-server

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE_NAME}
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - postgres
      - airflow-init
      - airflow-api-server
    env_file:
      - .env
    environment:
      <<: *airflow-common-env
      PYTHONPATH: /opt/airflow
    user: "${AIRFLOW_UID}:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: scheduler

  airflow-dag-processor:
    image: ${AIRFLOW_IMAGE_NAME}
    container_name: airflow-dag-processor
    restart: always
    depends_on:
      - postgres
      - airflow-init
    env_file:
      - .env
    environment:
      <<: *airflow-common-env
      PYTHONPATH: /opt/airflow
    user: "${AIRFLOW_UID}:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - ./scripts:/opt/airflow/scripts
    command: dag-processor

volumes:
  postgres-db-volume: